import 'dart:convert';
import 'dart:io';

import 'package:arm_tooling_core/arm_tooling_core.dart';

import 'conformance_cases.dart';

/// Writes `arm/contract/conformance.json` from [armFingerprintCases] and
/// [armSanitizerCases], using `tooling_core` as the reference.
///
///   dart run tool/generate_conformance.dart     (from arm/tooling_core)
///
/// Regenerate only when the reference is meant to change. Every other client's
/// test then fails until it matches — which is the point.
void main() {
  final file = File('../contract/conformance.json');
  file.writeAsStringSync(
    '${const JsonEncoder.withIndent('  ').convert(buildArmConformance())}\n',
  );
  stdout.writeln('Wrote ${file.path}');
}

Map<String, Object?> buildArmConformance() => <String, Object?>{
  'description':
      'ARM document contract conformance set (Feature 1.6.1). Generated by '
      'arm/tooling_core/tool/generate_conformance.dart; do not edit by hand.',
  'fingerprints': <Map<String, Object?>>[
    for (final c in armFingerprintCases) _fingerprintCase(c),
  ],
  'sanitizer': <Map<String, Object?>>[
    for (final c in armSanitizerCases)
      <String, Object?>{
        'name': c['name'],
        'input': c['input'],
        'expected': sanitizeArmMap(
          Map<String, dynamic>.from(c['input']! as Map),
        ),
      },
  ],
};

Map<String, Object?> _fingerprintCase(Map<String, Object?> c) {
  final fingerprint = buildArmFingerprint(
    feature: c['feature']! as String,
    operation: c['operation']! as String,
    errorType: c['errorType']! as String,
    message: c['message']! as String,
    stackTrace: StackTrace.fromString(c['stack']! as String),
  );
  return <String, Object?>{
    ...c,
    'expected': <String, Object?>{
      'fingerprint': fingerprint,
      'issueId': buildArmIssueId(fingerprint),
    },
  };
}
