import 'dart:convert';

import 'package:arm_tooling_core/arm_tooling_core.dart';
import 'package:citadel_arm_service/citadel_arm_contracts.dart';
import 'package:test/test.dart';

/// The two halves of a ticket opened from an error dialog.
///
/// The SDK writes the document straight into the client's own Firestore, and
/// this service reads it back. Nothing else holds those two shapes together —
/// so when one of them changes, this fails rather than a customer's first
/// ticket being unreadable in the Console.
void main() {
  test('a ticket the SDK writes is a ticket the service can read', () {
    final Map<String, dynamic> document = buildArmTicketDocumentMap(
      ticketId: 'ticket_a',
      updateId: 'ticket_a_1',
      request: const ArmTicketRequest(
        title: 'Checkout will not submit',
        description: 'It spins and then nothing happens.',
        contact: 'buyer@example.com',
        caseId: 'ARM-20260831-AB12CD34',
        issueId: 'issue_checkout',
        sessionId: 'session-1',
      ),
      createdAt: DateTime.utc(2026, 8, 31, 3),
      indexedUpdatedAt: 'server-timestamp',
    );

    final ArmTicketRecord ticket = decodeArmTicketRecord(
      jsonDecode(document['ticket'] as String),
      r'$',
    );

    expect(ticket.ticketId, 'ticket_a');
    expect(ticket.status, ArmTicketStatus.open);
    expect(ticket.caseIds, <String>['ARM-20260831-AB12CD34']);
    expect(ticket.issueId, 'issue_checkout');
    expect(ticket.sessionId, 'session-1');
    expect(ticket.createdBy, 'citadel_arm_client');
    expect(ticket.updates.single.authorKind, ArmTicketAuthorKind.endUser);
    // Opened with nobody named, so the link is the access control — and the
    // public view drops exactly the coordinates asserted above.
    expect(ticket.isPublicByLink, isTrue);
    final ArmTicketRecord public = armPublicTicketView(ticket);
    expect(public.caseIds, isEmpty);
    expect(public.sessionId, isNull);
    expect(public.reporterContact, isNull);
  });

  test('a session id the SDK mints is a resource id the service accepts', () {
    final String sessionId = buildArmSessionId('citadel-platform');
    final Map<String, dynamic> document = buildArmTicketDocumentMap(
      ticketId: buildArmTicketId(),
      updateId: 'update_1',
      request: ArmTicketRequest(
        title: 'A',
        description: 'B',
        caseId: buildArmCaseId(),
        issueId: buildArmIssueId('fingerprint'),
        sessionId: sessionId,
      ),
      createdAt: DateTime.utc(2026, 8, 31, 3),
      indexedUpdatedAt: 'server-timestamp',
    );

    // The ids are generated by three different builders and validated by one
    // grammar. A builder that starts emitting something the grammar refuses
    // would otherwise only be found by a customer.
    expect(
      () => decodeArmTicketRecord(
        jsonDecode(document['ticket'] as String),
        r'$',
      ),
      returnsNormally,
    );
  });
}
